// AUTO-GENERATED by `npm run gen:themes` — JANGAN edit manual.
// Tambah theme baru: buat file themes/NamaTema.tsx + `export const themeMeta = {...}`, lalu restart dev.

import type { ComponentType } from "react";
import type { TickerThemeProps } from "./types";
import CleanTheme from "./Clean";
import NeonTheme from "./Neon";
import StandardTheme from "./Standard";

export const tickerThemeComponents: Record<string, ComponentType<TickerThemeProps>> = {
  "clean": CleanTheme,
  "neon": NeonTheme,
  "standard": StandardTheme,
};

export const TICKER_THEME_OPTIONS = [
  { value: "clean", label: "Clean - Teks Polos" },
  { value: "neon", label: "Neon - Glow Accent" },
  { value: "standard", label: "Standard - Bar + Badge" },
] as const;

export const TICKER_THEME_DEFAULT = "standard";
