// AUTO-GENERATED by `npm run gen:themes` — JANGAN edit manual.
// Tambah tema baru: buat file presets/namaTema.ts (export default defineTheme({...})), lalu restart dev / jalankan npm run gen:themes.

import type { ThemePresetMap } from "../types";
import compact from "./compact";
import cute from "./cute";
import cyber from "./cyber";
import dark from "./dark";
import light from "./light";
import minimal from "./minimal";
import neon from "./neon";
import pokemon from "./pokemon";
import tiktok from "./tiktok";
import vtuber from "./vtuber";

export const themePresets: ThemePresetMap = {
  compact,
  cute,
  cyber,
  dark,
  light,
  minimal,
  neon,
  pokemon,
  tiktok,
  vtuber,
};

// Optional: export by category for filtered UI (dibaca dari field `category` tiap preset)
export const themeCategories = {
  "minimal": ["compact", "minimal"],
  "cute": ["cute"],
  "gaming": ["cyber", "neon"],
  "core": ["dark", "light"],
  "anime": ["pokemon", "tiktok", "vtuber"],
} as const;
