// AUTO-GENERATED by `npm run gen:themes` - JANGAN edit manual.
// Tambah theme baru: buat file themes/NamaTema.tsx + `export const themeMeta = {...}`, lalu restart dev.

import type { ComponentType } from "react";
import type { ChatThemeProps } from "./types";
import BoxedTheme from "./Boxed";
import BrutalistTheme from "./Brutalist";
import BubbleTheme from "./Bubble";
import CleanTheme from "./Clean";
import CuteTheme from "./Cute";
import PerCharTheme from "./PerChar";
import PlainTheme from "./Plain";
import StandardTheme from "./Standard";

export const chatThemeComponents: Record<string, ComponentType<ChatThemeProps>> = {
  "boxed": BoxedTheme,
  "brutalist": BrutalistTheme,
  "bubble": BubbleTheme,
  "clean": CleanTheme,
  "cute": CuteTheme,
  "perchar": PerCharTheme,
  "plain": PlainTheme,
  "standard": StandardTheme,
};

export const CHAT_THEME_OPTIONS = [
  { value: "boxed", label: "Boxed - Card dengan Header" },
  { value: "brutalist", label: "Brutalist" },
  { value: "bubble", label: "Bubble - Putih WA-style" },
  { value: "clean", label: "Clean - Baris Minimalis" },
  { value: "cute", label: "Cute - Lavender Pastel" },
  { value: "perchar", label: "Per-Char - Bubble + Huruf Mengetik" },
  { value: "plain", label: "Plain" },
  { value: "standard", label: "Standard - Dark Glass" },
] as const;

export const CHAT_THEME_DEFAULT = "standard";
