// Unified Google Fonts - single source for ALL widgets (chat/poll/clock/media/lyrics/overlay)
// Semua font diambil dari Google Fonts, select diisi dari sini. Jangan hardcode fontsList di widget.

export const WIDGET_FONTS = [
  'Outfit',
  'Inter',
  'Poppins',
  'Plus Jakarta Sans',
  'Space Grotesk',
  'Manrope',
  'Urbanist',
  'Barlow',
  'Be Vietnam Pro',
  'JetBrains Mono',
  'Space Mono',
  'Bebas Neue',
  'Anton',
  'Righteous',
  'Fredoka',
  'Comfortaa',
  'Nunito',
  'Quicksand',
  'Montserrat',
  'Roboto',
  'Oswald',
  'Orbitron',
  'Lato',
  'Open Sans',
  'Noto Sans',
  'Ubuntu',
  'Source Sans 3',
  'Fira Sans',
  'Playfair Display',
  'Merriweather',
] as const;

export type WidgetFont = typeof WIDGET_FONTS[number];

// Untuk UI select yang butuh label/category (dipakai overlay juga)
export const GOOGLE_FONTS_META: { value: string; label: string; category: string }[] = [
  { value: 'Outfit', label: 'Outfit', category: 'Sans' },
  { value: 'Inter', label: 'Inter', category: 'Sans' },
  { value: 'Poppins', label: 'Poppins', category: 'Sans' },
  { value: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans', category: 'Sans' },
  { value: 'Space Grotesk', label: 'Space Grotesk', category: 'Sans' },
  { value: 'Manrope', label: 'Manrope', category: 'Sans' },
  { value: 'Urbanist', label: 'Urbanist', category: 'Sans' },
  { value: 'Barlow', label: 'Barlow', category: 'Sans' },
  { value: 'Be Vietnam Pro', label: 'Be Vietnam Pro', category: 'Sans' },
  { value: 'Montserrat', label: 'Montserrat', category: 'Sans' },
  { value: 'Roboto', label: 'Roboto', category: 'Sans' },
  { value: 'Oswald', label: 'Oswald', category: 'Sans' },
  { value: 'Lato', label: 'Lato', category: 'Sans' },
  { value: 'Open Sans', label: 'Open Sans', category: 'Sans' },
  { value: 'Noto Sans', label: 'Noto Sans', category: 'Sans' },
  { value: 'Ubuntu', label: 'Ubuntu', category: 'Sans' },
  { value: 'Source Sans 3', label: 'Source Sans 3', category: 'Sans' },
  { value: 'Fira Sans', label: 'Fira Sans', category: 'Sans' },
  { value: 'Playfair Display', label: 'Playfair Display', category: 'Serif' },
  { value: 'Merriweather', label: 'Merriweather', category: 'Serif' },
  { value: 'JetBrains Mono', label: 'JetBrains Mono', category: 'Mono' },
  { value: 'Space Mono', label: 'Space Mono', category: 'Mono' },
  { value: 'Bebas Neue', label: 'Bebas Neue', category: 'Display' },
  { value: 'Anton', label: 'Anton', category: 'Display' },
  { value: 'Righteous', label: 'Righteous', category: 'Display' },
  { value: 'Fredoka', label: 'Fredoka', category: 'Display' },
  { value: 'Comfortaa', label: 'Comfortaa', category: 'Display' },
  { value: 'Nunito', label: 'Nunito', category: 'Display' },
  { value: 'Quicksand', label: 'Quicksand', category: 'Display' },
  { value: 'Orbitron', label: 'Orbitron', category: 'Display' },
];
